config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { saml_sessions: 'saml_sessions' }
  root 'states#index'
  get 'faq', to: 'pages#faq'
  get 'search', controller: :main
  get 'login', to: 'pages#login'
  get 'election', to: 'pages#choose_election'
  get 'municipalities', to: 'states#index'
  get 'wartung', to: 'pages#construction'
  get 'sessions/create', to: 'sessions#create'
  get 'election_display', to: 'pages#election_display'

  resources :states
  resources :districts
  resources :precincts
  resources :municipalities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :election
  belongs_to :state
  has_many :precincts
  has_many :municipalities
  default_scope { order(district_identifier: :asc) }
  scope :election, -> (election) { where(election: election) }

  def municipalities
    Municipality.where(district: self)
  end

  def precincts
    Precinct.where(district: self)
  end
end

app/models/election.rb
class Election < ApplicationRecord
  has_many :districts
  has_many :municipalities
  has_many :precincts
end

app/models/municipality.rb
class Municipality < ApplicationRecord
  belongs_to :election
  belongs_to :district
  has_many :precincts
  default_scope { order(name: :asc) }
  scope :election, -> (election) { where(election: election) }

  def state
    self.district.state
  end
end

app/models/precinct.rb
class Precinct < ApplicationRecord
  belongs_to :election
  belongs_to :district
  belongs_to :municipality
  scope :election, -> (election) { where(election: election) }
end

app/models/state.rb
class State < ApplicationRecord
  has_many :districts
end

app/models/user.rb
class User < ApplicationRecord
  devise :saml_authenticatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def authenticated_user?
      unless user_signed_in?
        redirect_to login_path, notice: 'Anmeldung erforderlich'
      end
    end

    def current_election
      @current_election = Election.find_by_id(session[:current_election_id]) || Election.first
    end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :authenticated_user?
  before_action :current_election

  def index
    @districts = District.election(@current_election).
      sort_by { |d| d.district_identifier.split(' ').map(&:to_i) }
  end

  def show
    if @current_election.state == 'he'
      @district = District.election(@current_election).
        find_by(district_identifier: params[:id])
      if params['gemeinde'] == '1'
        @municipalities = Municipality.election(@current_election).
          where(district: @district).sort_alphabetical_by(&:name)
        render 'show_ltwh_municipalities'
      else
        @precincts = Precinct.election(@current_election).
          where(district: @district).sort_by { |p| p.district_score }.reverse!
        render 'show_ltwh'
      end
    elsif @current_election.state == 'by'
      @district = District.election(@current_election).
        find_by(district_identifier: params[:id])
      if params['gemeinde'] == '1'
        @municipalities = Municipality.election(@current_election).
          where(district: @district).sort_alphabetical_by(&:name)
        render 'show_ltwb_municipalities'
      else
        @precincts = Precinct.election(@current_election).
          where(district: @district).sort_by { |p| p.district_score }.reverse!
        render 'show_ltwb'
      end
    else
      @district = District.election(@current_election).
        find_by(district_identifier: params[:id])
      if params['gemeinde'] == '1'
        @municipalities = Municipality.election(@current_election).
          where(district: @district).sort_alphabetical_by(&:name)
        render 'show_municipalities'
      else
        @precincts = Precinct.election(@current_election).
          where(district: @district).sort_by { |p| p.district_rank }
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :current_election

  def search
    if @current_election.state == 'all'
      @states = State.ransack(name_cont: search_params).result(distinct: true)
    end
    @districts = District.election(@current_election).
      ransack(name_cont: search_params).result(distinct: true)
    @municipalities = Municipality.election(@current_election).
      ransack(name_cont: search_params).result(distinct: true)

    respond_to do |format|
      format.html {}
      format.json {
        if @current_election.state == 'all'
          @states = @states.limit(3)
        end
        @districts = @districts.limit(6)
        @municipalities = @municipalities.limit(10)
      }
    end
  end

  private

  def search_params
    params[:q].gsub(' ','').gsub(/[^0-9a-z\-üßöäA-ZÜÖÄ ]/i, '')
  end
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :authenticated_user?
  before_action :current_election

  def index
    @municipalities = Municipality.election(@current_election).all
  end

  def show
    find_or_redirect
    if @current_election.state == 'he'
      @precincts = Precinct.election(@current_election).
        where(municipality: @municipality).
        sort_by { |p| p.district_score }.reverse!
      render 'show_ltwh_municipality'
    elsif @current_election.state == 'by'
      @precincts = Precinct.election(@current_election).
        where(municipality: @municipality).
        sort_by { |p| p.district_score }.reverse!
      render 'show_ltwb_municipality'
    else
      @precincts = Precinct.election(@current_election).
        where(municipality: @municipality).sort_by { |p| p.district_rank }
    end
  end

  private

  def find_or_redirect
    unless @municipality = Municipality.election(@current_election).
        find_by(municipality_identifier: params[:id])
      redirect_to :root
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticated_user?, only: [:faq, :choose_election]
  before_action :current_election

  def faq
  end

  def login
  end

  def choose_election
    @elections = Election.all
  end

  def construction
  end
end

app/controllers/precincts_controller.rb
class PrecinctsController < ApplicationController
  before_action :authenticated_user?
  before_action :current_election
end

app/controllers/saml_sessions_controller.rb
class SamlSessionsController < Devise::SamlSessionsController
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:success, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:current_election_id] = params['election']
    redirect_to election_index
  end

  private
    def election_index
      if chosen_election.state == 'all'
        states_path
      else
        districts_path
      end
    end

    def chosen_election
      Election.find_by_id(session[:current_election_id]) || Election.first
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :authenticated_user?
  before_action :current_election

  def index
    @states = State.all.order 'name ASC'
  end

  def show
    @state = State.find(params[:id])
    @districts = District.election(@current_election).where(state: @state).
      sort_by { |d| d.district_identifier.to_i }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper

  def display_score score
    number_with_precision(score, precision: 2)
  end

  def id_cleaner identifier
    identifier.split('-')[0]
  end
end

app/views/districts/index.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        Start
.row
  - @districts.each do |d|
    .col-sm-2
      = link_to district_path(d.district_identifier) do
        .district-cell
          = d.district_identifier
          .district-info
            .item
              = pluralize(d.municipalities.count, 'Gemeinde', 'Gemeinden')
            .item
              = pluralize(d.precincts.count, 'Wahlbezirk', 'Wahlbezirke')

app/views/districts/show.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', states_path
      %li.breadcrumb-item.active
        = link_to @district.state.name, state_path(@district.state)
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    .heading
      = link_to 'Wahlbezirke', district_path(@district), class: 'switcher activeSwitcher'
      = link_to 'Gemeinden', district_path(@district, gemeinde: '1'), class: 'switcher passiveSwitcher'
      im Wahlkreis
      = @district.district_identifier
      = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th.title(data-sort="string")
            %span
            Gemeinde
          %th.data.number(data-sort="string")
            %span
            Wahlbezirk
          %th.data.number(data-sort="float")
            %span
            Score (WK)
          %th.data.number(data-sort="int")
            %span
            Rang (WK)
          %th.data.number(data-sort="int")
            %span
            Rang (Gemeinde)
          %th.filler
      %tbody
      - @precincts.each do |p|
        %tr
          %td
            = link_to p.municipality.name, municipality_path(p.municipality.municipality_identifier)
          %td.data.number
            = p.precinct_identifier
          %td.data.number
            = display_score p.district_score
          %td.data.number
            = p.district_rank
          %td.data.number
            = p.municipality_rank
          %td.filler

app/views/districts/show_ltwb.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      - if @current_election.state == 'all'
        %li.breadcrumb-item
          = link_to 'Start', states_path
        %li.breadcrumb-item.active
          = link_to @district.state.name, state_path(@district.state)
      - else
        %li.breadcrumb-item
          = link_to 'Start', districts_path
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    .heading
      = link_to 'Wahlbezirke', district_path(@district.district_identifier), class: 'switcher activeSwitcher'
      = link_to 'Gemeinden', district_path(@district.district_identifier, gemeinde: '1'), class: 'switcher passiveSwitcher'
      %br
      .districtInfo
        Wahlkreis
        = @district.district_identifier
        = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th.titleMini(data-sort="string")
            %span
            Gemeinde
          %th.dataMini.number(data-sort="string")
            %span
            Wahlbezirk
          %th.dataMini.number(data-sort="float")
            %span
            Score (WK)
          %th.bayernFiller
      %tbody
      - @precincts.each do |p|
        %tr
          %td
            = link_to p.municipality.name, municipality_path(p.municipality.municipality_identifier)
          %td.dataMini.number
            = p.precinct_identifier
          %td.dataMini.number
            = display_score p.district_score
          %td.bayernFiller

app/views/districts/show_ltwb_municipalities.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      - if @current_election.state == 'all'
        %li.breadcrumb-item
          = link_to 'Start', states_path
        %li.breadcrumb-item.active
          = link_to @district.state.name, state_path(@district.state)
      - else
        %li.breadcrumb-item
          = link_to 'Start', districts_path
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    .heading
      = link_to 'Wahlbezirke', district_path(@district.district_identifier), class: 'switcher passiveSwitcher'
      = link_to 'Gemeinden', district_path(@district.district_identifier, gemeinde: '1'), class: 'switcher activeSwitcher'
      %br
      .districtInfo
        Wahlkreis
        = @district.district_identifier
        = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Name
          %th(data-sort="integer")
            %span
            Gemeinde-ID
          %th(data-sort="integer")
            %span
            Gemeinde-Score
          %th.municipalityLtwhFiller
      %tbody
      - @municipalities.each do |m|
        %tr(data-link="#{municipality_path(m.municipality_identifier)}")
          %td
            = link_to m.name, municipality_path(m.municipality_identifier)
          %td
            = link_to id_cleaner(m.municipality_identifier),
              municipality_path(m.municipality_identifier)
          %td
            = m.district_score
          %td.municipalityLtwhFiller

app/views/districts/show_ltwh.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      - if @current_election.state == 'all'
        %li.breadcrumb-item
          = link_to 'Start', states_path
        %li.breadcrumb-item.active
          = link_to @district.state.name, state_path(@district.state)
      - else
        %li.breadcrumb-item
          = link_to 'Start', districts_path
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    .heading
      = link_to 'Wahlbezirke', district_path(@district.district_identifier), class: 'switcher activeSwitcher'
      = link_to 'Gemeinden', district_path(@district.district_identifier, gemeinde: '1'), class: 'switcher passiveSwitcher'
      %br
      .districtInfo
        Wahlkreis
        = @district.district_identifier
        = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th.titleLtwh(data-sort="string")
            %span
            Gemeinde
          %th.dataMini.number(data-sort="string")
            %span
            Wahlbezirk
          %th.data.number(data-sort="string")
            %span
            Bezeichnung
          %th.dataMini.number(data-sort="string")
            %span
            BTW-WK
          %th.dataMini.number(data-sort="float")
            %span
            Score (WK)
          %th.filler
      %tbody
      - @precincts.each do |p|
        %tr
          %td.ltwh
            = link_to p.municipality.name, municipality_path(p.municipality.municipality_identifier)
          %td.dataMini.number
            = p.precinct_identifier
          %td.data.number
            = display_score p.name
          %td.dataMini.number
            = p.btw_district.to_s
          %td.dataMini.number
            = display_score p.district_score
          %td.filler

app/views/districts/show_ltwh_municipalities.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      - if @current_election.state == 'all'
        %li.breadcrumb-item
          = link_to 'Start', states_path
        %li.breadcrumb-item.active
          = link_to @district.state.name, state_path(@district.state)
      - else
        %li.breadcrumb-item
          = link_to 'Start', districts_path
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    .heading
      = link_to 'Wahlbezirke', district_path(@district.district_identifier), class: 'switcher passiveSwitcher'
      = link_to 'Gemeinden', district_path(@district.district_identifier, gemeinde: '1'), class: 'switcher activeSwitcher'
      %br
      .districtInfo
        Wahlkreis
        = @district.district_identifier
        = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Name
          %th(data-sort="integer")
            %span
            Gemeinde-ID
          %th(data-sort="integer")
            %span
            Gemeinde-Score
          %th.municipalityLtwhFiller
      %tbody
      - @municipalities.each do |m|
        %tr(data-link="#{municipality_path(m.municipality_identifier)}")
          %td
            = link_to m.name, municipality_path(m.municipality_identifier)
          %td
            = link_to id_cleaner(m.municipality_identifier),
              municipality_path(m.municipality_identifier)
          %td
            = m.district_score
          %td.municipalityLtwhFiller

app/views/districts/show_municipalities.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', states_path
      %li.breadcrumb-item.active
        = link_to @district.state.name, state_path(@district.state)
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    .heading
      = link_to 'Wahlbezirke', district_path(@district), class: 'switcher passiveSwitcher'
      = link_to 'Gemeinden', district_path(@district, gemeinde: '1'), class: 'switcher activeSwitcher'
      im Wahlkreis
      = @district.district_identifier
      = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Name
          %th(data-sort="integer")
            %span
            Gemeinde-ID
          %th.municipalityFiller
      %tbody
      - @municipalities.each do |m|
        %tr(data-link="#{municipality_path(m.municipality_identifier)}")
          %td
            = link_to m.name, municipality_path(m.municipality_identifier)
          %td
            = link_to id_cleaner(m.municipality_identifier),
              municipality_path(m.municipality_identifier)
          %td.municipalityFiller

app/views/districts/show_municipality.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', states_path
      %li.breadcrumb-item.active
        = link_to @district.state.name, state_path(@district.state)
      %li.breadcrumb-item
        Wahlkreis
        = @district.district_identifier
.row
  .col-sm-12
    %h3
      Gemeinden im Wahlkreis
      = @district.district_identifier
      = @district.name

.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Name
          %th(data-sort="integer")
            %span
            Gemeinde-ID
      %tbody
      - @municipalities.each do |m|
        %tr(data-link="#{municipality_path(m.municipality_identifier)}")
          %td
            = link_to m.name, municipality_path(m.municipality_identifier)
          %td
            = link_to m.municipality_identifier,
              municipality_path(m.municipality_identifier)

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-sm-4.footerContent
        = link_to 'Code on GitHub', 'https://github.com/greenvault/wahlbezirke'

app/views/layouts/_header.html.erb
<nav class='navbar navbar-toggleable-md navbar-inverse bg-inverse' id= 'headerNavbar'>
  <div class='container'>
    <% if user_signed_in? %>
      <% if @current_election.state == 'all' %>
        <a class="navbar-brand" href="/states">
      <% else %>
        <a class="navbar-brand" href="/districts">
      <% end %>
    <% else %>
      <a class="navbar-brand" href="/">
    <% end %>
      <%= image_tag 'logo-gruen.jpg', width: 30, height: 30, class: 'd-inline-block align-top' %>
      <span class='logo-text'>PotentialGrün</span>
    </a>
    <div class='election-indicator'>Aktive Wahl: hallo</div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <% if user_signed_in? %>
        <%= form_tag('/search', local: true, method: :get, class: 'form-inline searchModule' ) do %>
          <%= text_field_tag(:q, nil, data: { behavior: 'autocomplete' },
                             placeholder: 'WK, Gemeinde, ...', id: 'searchField',
                            class: 'form-control mr-sm-2') %>
                          <%= button_tag('Suchen', class: 'btn btn-outline-success my-2 my-sm-0',
                                         id: 'searchSubmit', type: 'submit') %>
        <% end %>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/faq">FAQ / Anleitung</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<% if user_signed_in? %>
  <div class='container indicatorRow'>
    <div class='row'>
      <div class='col-sm-12'>
        <%= render 'layouts/indicator' %>
      </div>
    </div>
  </div>
<% end %>

<% flash.each do |key, value| %>
  <div class='container <%= "fb-#{key}" %>' id="flashBox">
    <div class="row">
      <div class="col-sm-12">
        <div class='message'>
          <%= value %>
          <span class='pointer'><%= fa_icon 'times-circle' %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_indicator.html.haml
.indicator
  = link_to "Aktive Wahl: #{@current_election.name}", election_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <head>
    <title>
      <%= if content_for?(:title) then yield(:title) + ' | ' end %>
      PotentialGrün
    </title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <%= yield %>
    </div>
    <%- render 'layouts/footer' %>
  </body>
</html>

app/views/main/search.html.erb
<% if @current_election.state == 'all' %>
  <div class="row">
    <div class="col-sm-4">
      <h1>Länder</h1>
      <% @states.each do |state| %>
        <p><%= link_to state.name, state %></p>
      <% end %>
    </div>
<% end %>

  <div class="col-sm-4">
    <h1>Wahlbezirke</h1>
    <% @districts.each do |district| %>
      <p><%= link_to district.name, district %></p>
    <% end %>
  </div>

  <div class="col-sm-4">
    <h1>Gemeinden</h1>
    <% @municipalities.each do |municipality| %>
      <p><%= link_to municipality.name, municipality_path(municipality.municipality_identifier) %></p>
    <% end %>
  </div>
</div>

app/views/municipalities/show.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', states_path
      %li.breadcrumb-item
        = link_to @municipality.state.name, state_path(@municipality.state)
      %li.breadcrumb-item.active
        = link_to "Wahlkreis #{@municipality.district.district_identifier}",
          district_path(@municipality.district.district_identifier, gemeinde: '1')
      %li.breadcrumb-item
        Gemeinde
        = @municipality.name
.row
  .col-sm-12
    %h3
      Wahlbezirke in
      = @municipality.name
      = " (#{id_cleaner(@municipality.municipality_identifier)})"
.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Wahlbezirk
          %th(data-sort="float")
            %span
            Targeting-Score im Wahlkreis
          %th(data-sort="int")
            %span
            Targeting-Rang im Wahlkreis
          %th(data-sort="int")
            %span
            Targeting-Rang in Gemeinde
      %tbody
      - @precincts.each do |p|
        %tr
          %td
            = p.precinct_identifier
          %td
            = display_score p.district_score
          %td
            = p.district_rank
          %td
            = p.municipality_rank

app/views/municipalities/show_ltwb_municipality.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', districts_path
      %li.breadcrumb-item.active
        = link_to "Wahlkreis #{@municipality.district.district_identifier}",
          district_path(@municipality.district.district_identifier, gemeinde: '1')
      %li.breadcrumb-item
        Gemeinde
        = @municipality.name
.row
  .col-sm-12
    %h3
      Wahlbezirke in
      = @municipality.name
      = " (#{id_cleaner(@municipality.municipality_identifier)})"
.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Wahlbezirk
          %th(data-sort="float")
            %span
            Targeting-Score im Wahlkreis
          %th.bayernFiller
      %tbody
      - @precincts.each do |p|
        %tr
          %td
            = p.precinct_identifier
          %td
            = display_score p.district_score
          %td.bayernFiller

app/views/municipalities/show_ltwh_municipality.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', states_path
      %li.breadcrumb-item
        = link_to @municipality.state.name, state_path(@municipality.state)
      %li.breadcrumb-item.active
        = link_to "Wahlkreis #{@municipality.district.district_identifier}",
          district_path(@municipality.district.district_identifier, gemeinde: '1')
      %li.breadcrumb-item
        Gemeinde
        = @municipality.name
.row
  .col-sm-12
    %h3
      Wahlbezirke in
      = @municipality.name
      = " (#{id_cleaner(@municipality.municipality_identifier)})"
.row
  .col-sm-12
    %table.table.table-hover.table-striped.tablesorter
      %thead
        %tr
          %th(data-sort="string")
            %span
            Wahlbezirk
          %th(data-sort="string")
            %span
            Wahlbezirk-Name
          %th(data-sort="float")
            %span
            Targeting-Score im Wahlkreis
          %th.filler
      %tbody
      - @precincts.each do |p|
        %tr
          %td
            = p.precinct_identifier
          %td
            = p.name
          %td
            = display_score p.district_score
          %td.filler

app/views/pages/choose_election.html.haml
.row
  .col-sm-12.col-md-8
    %h1 Bitte gewünschte Wahl anklicken

.row
  - @elections.each do |e|
    .col-sm-3.election-card
      %a(href="/sessions/create?election=#{e.id}")
        .card
          .flag
            P
          %h2
            = e.name
          %p.election-comment
            = e.comment

app/views/pages/construction.html.haml
.row
  .col-sm-12.text-center
    = image_tag 'roadblock.png', id: 'roadblock', width: '20%'
    %h2 Wartungsmodus
    %p Wir überarbeiten PotentialGrün derzeit.

app/views/pages/faq.html.haml
.row
  .col-sm-10
    %h1 Häufige Fragen / Frequently asked questions (FAQ)

    = render 'faqcontent'

app/views/pages/login.html.haml
.row
  .col-sm-12.col-md-8
    %h1 Anmeldung erforderlich
    .loginBox
      %a.loginButton.btn.btn-lg.btn-primary(href='/users/saml/sign_in' data-role='button')
        Login mit netz.gruene.de
.row
  .col-sm-12.col-md-8
    %p
      Das Passwort kann unter
      = link_to 'netz.gruene.de', 'https://netz.gruene.de'
      zurückgesetzt werden. Falls du deine Anmeldedaten nicht (mehr) kennst, schreibe eine Mail an netz@gruene.de

app/views/states/index.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to 'Start', states_path
      %li.breadcrumb-item.active
        Bundesländer
.row
  .col-sm-12
    - @states.each do |s|
      %p
        = link_to s.name, state_path(s)

app/views/states/show.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      - if @current_election.state == 'all'
        %li.breadcrumb-item
          = link_to 'Start', states_path
        %li.breadcrumb-item.active
          = @state.name
      - else
        %li.breadcrumb-item
          Start
.row
  .col-sm-12
    %h3
      Wahlkreise in
      = @state.name
.row
  - @districts.each do |d|
    .col-sm-2
      = link_to district_path(d.district_identifier) do
        .district-cell
          = d.district_identifier
          .district-info
            .item
              = pluralize(d.municipalities.count, 'Gemeinde', 'Gemeinden')
            .item
              = pluralize(d.precincts.count, 'Wahlbezirk', 'Wahlbezirke')